#homeassistant:
#  # Name of the location where Home Assistant is running
#  name: Home
#  # Location required to calculate the time the sun rises and sets
#  latitude: !secret zone_rge_latitude
#  longitude: !secret zone_rge_longitude
#  # Impacts weather/sunrise data (altitude above sea level in meters)
#  elevation: 0
#  # metric for Metric, imperial for Imperial
#  unit_system: metric
#  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#  time_zone: UTC
##  # Customization file
##  customize: !include customize.yaml

homeassistant:
  name: RGE
  unit_system: metric
  time_zone: UTC
  latitude: !secret zone_rge_latitude
  longitude: !secret zone_rge_longitude
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_api_password

# Enables the frontend
frontend:

# Enables configuration UI
config:

backup:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
#http:
#  api_password: !secret http_api_password

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

amcrest: 
  - host: 10.0.1.52 
    username: admin 
    password: !secret mqtt_password 
    binary_sensors:
      - motion_detected
      - online
    sensors:
      - sdcard
      - ptz_preset

#binary_sensor:
#  - platform: mqtt
#    name: "Door Detector"
#    device_class: "door"
#    state_topic: "hass/message/sensorist/rge"
#    payload_on: 1
#    payload_off: 0
#    value_template: "{{ value_json['35055']['value'] }}"
#    json_attributes_topic: "hass/message/sensorist/rge"

# Sensors
#sensor:
#  - platform: mqtt
#    name: "RGE Door Temperature"
#    state_topic: "hass/message/sensorist/rge"
#    unit_of_measurement: '째C'
#    value_template: "{{ value_json['35036']['value'] }}"
#    json_attributes_topic: "hass/message/sensorist/rge"
#  - platform: mqtt
#    name: "RGE Bedroom Temperature "
#    state_topic: "hass/message/sensorist/rge"
#    unit_of_measurement: '째C'
#    value_template: "{{ value_json['35040']['value'] }}"
#    json_attributes_topic: "hass/message/sensorist/rge"
  - platform: opensky
    radius: 15
    name: rgesky
#  - platform: mqtt
#    name: RGE Callsign
#    unique_id: rgesky_callsign
#    state_topic: "hass/message/rgesky/callsign"
  - platform: trafikverket_weatherstation
    name: Trafikverket Borgholm
    api_key: 44c57611abe74a599f3d02d97dda940f
    station: Borgholm
    monitored_conditions:
        - air_temp
        - road_temp
        - humidity
        - precipitation
        - wind_direction
        - wind_direction_text
        - wind_speed
        - wind_speed_max
        - precipitation_amount
        - precipitation_amountname

tellduslive:

# Text to speech
tts:
  - platform: google_translate

# Cloud
cloud:

#speedtestdotnet:
#manual only now

#wwlln:
#  radius: 50
#not supported

lutron_caseta:
    host: 10.0.1.41
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

camera:
  - platform: mjpeg
    name: !secret camera_rge_front_name
    mjpeg_url: !secret camera_rge_front_url
  - platform: mjpeg
    name: !secret camera_rge_lroom_name
    mjpeg_url: !secret camera_rge_lroom_url
  - platform: mjpeg
    name: !secret camera_rge_dtop_name
    mjpeg_url: !secret camera_rge_dtop_url
  - platform: mjpeg
    name: !secret camera_rge_acer_name
    mjpeg_url: !secret camera_rge_acer_url
  - platform: mjpeg
    name: !secret camera_rge_attic_name
    mjpeg_url: !secret camera_rge_attic_url
  - platform: mjpeg
    name: !secret camera_rge_outhouse_name
    mjpeg_url: !secret camera_rge_outhouse_url

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.0/24, 192.168.50.0/24, 192.168.0.0/24
    home_interval: 1
    exclude:
      - 192.168.1.80

#  - platform: nmap_tracker
#    hosts: ipcam-back.lan
#    home_interval: 1
#  - platform: nmap_tracker
#    hosts: ipcam-front.lan
#    home_interval: 1
#  - platform: nmap_tracker
#    hosts: ipcam-living.lan
#    home_interval: 1

influxdb:

iperf3:
  hosts:
    - host: !secret hosts_ict 
      port: 5001

mqtt:
  broker: !secret mqtt_host
  port: !secret mqtt_port
  username: !secret mqtt_user
  password: !secret mqtt_password
  certificate: /etc/ssl/certs/ca-certificates.crt
  binary_sensor:
    - name: "Door Detector"
      device_class: "door"
      state_topic: "hass/message/sensorist/rge"
      payload_on: 1
      payload_off: 0
      value_template: "{{ value_json['35055']['value'] }}"
      json_attributes_topic: "hass/message/sensorist/rge"
  sensor:
    - name: "RGE Door Temperature"
      state_topic: "hass/message/sensorist/rge"
      unit_of_measurement: '째C'
      value_template: "{{ value_json['35036']['value'] }}"
      json_attributes_topic: "hass/message/sensorist/rge"
    - name: "RGE Bedroom Temperature "
      state_topic: "hass/message/sensorist/rge"
      unit_of_measurement: '째C'
      value_template: "{{ value_json['35040']['value'] }}"
      json_attributes_topic: "hass/message/sensorist/rge"
    - name: RGE Callsign
      unique_id: rgesky_callsign
      state_topic: "hass/message/rgesky/callsign"

mqtt_statestream:
  base_topic: hass/statestream
  publish_attributes: true
  publish_timestamps: true

mqtt_eventstream:
  publish_topic: hass/eventstream/slaves/rge
  subscribe_topic: hass/eventstream/master

ffmpeg:

panel_iframe:
  grafana:
    title: 'Grafana'
    url: http://192.168.50.10:3000
    icon: mdi:gauge

upnp:
#  sensors: true
#  port_mapping: false
  
lovelace:
  mode: yaml

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
light: !include lights.yaml

logger:
  default: warning
  logs:
    homeassistant.components.mqtt: warning