- platform: group
  name: Silverlyckan Lights
  entities:
    - light.bathroom_bathroom_light
    - light.salle_a_manger_dinner_table
    - light.bedroom_basement_bedroom_roof
    - light.exterieur_balcony_light
    - light.media_room_chandelier
    - light.media_room_hood