- platform: template
  sensors:
    person_present:
      friendly_name: 'Person Present'
      device_class: presence
      entity_id:
        - sensor.time
      value_template: >
        {% set ns = namespace(found=false) %}
        {% for state in states.person %}
          {% if state.state == 'home' %}
            {% set ns.found = true %}
          {% endif %}
        {% endfor %}
        {{ns.found}}